/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.danilorocha.view;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author danilo
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        decorateTableTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEmptyList = new javax.swing.JPanel();
        labelEmptyListIcon = new javax.swing.JLabel();
        labelEmptyListTitle = new javax.swing.JLabel();
        labelEmptyListSubtitle = new javax.swing.JLabel();
        panelContents = new javax.swing.JPanel();
        panelTitleBar = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelSubtitle = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();
        panelProjects = new javax.swing.JPanel();
        labelProjectsTitle = new javax.swing.JLabel();
        labelProjectsIcon = new javax.swing.JLabel();
        panelTasks = new javax.swing.JPanel();
        labelTasksTitle = new javax.swing.JLabel();
        labelTasksIcon = new javax.swing.JLabel();
        panelProjectsList = new javax.swing.JPanel();
        scrollPanelProjects = new javax.swing.JScrollPane();
        listProjects = new javax.swing.JList<>();
        panelContentsTask = new javax.swing.JPanel();
        scrollPanelTasks = new javax.swing.JScrollPane();
        tableTasks = new javax.swing.JTable();

        panelEmptyList.setBackground(new java.awt.Color(255, 255, 255));

        labelEmptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelEmptyListTitle.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        labelEmptyListTitle.setForeground(new java.awt.Color(0, 153, 102));
        labelEmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmptyListTitle.setText("Não há tarefas no momento :D");

        labelEmptyListSubtitle.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 12)); // NOI18N
        labelEmptyListSubtitle.setForeground(new java.awt.Color(153, 153, 153));
        labelEmptyListSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmptyListSubtitle.setText("Click no botão de \"+\" para adicionar nova tarefa");

        javax.swing.GroupLayout panelEmptyListLayout = new javax.swing.GroupLayout(panelEmptyList);
        panelEmptyList.setLayout(panelEmptyListLayout);
        panelEmptyListLayout.setHorizontalGroup(
            panelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEmptyListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(labelEmptyListSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEmptyListLayout.setVerticalGroup(
            panelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmptyListLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(labelEmptyListIcon)
                .addGap(18, 18, 18)
                .addComponent(labelEmptyListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEmptyListSubtitle)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(600, 700));

        panelContents.setBackground(java.awt.Color.white);
        panelContents.setName(""); // NOI18N

        panelTitleBar.setBackground(new java.awt.Color(0, 153, 102));
        panelTitleBar.setBorder(new javax.swing.border.MatteBorder(null));

        labelTitle.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 36)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("Tarefas");

        labelSubtitle.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 12)); // NOI18N
        labelSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        labelSubtitle.setText("Anote tudo, não esqueça nada!");

        javax.swing.GroupLayout panelTitleBarLayout = new javax.swing.GroupLayout(panelTitleBar);
        panelTitleBar.setLayout(panelTitleBarLayout);
        panelTitleBarLayout.setHorizontalGroup(
            panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleBarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(labelIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSubtitle)
                    .addComponent(labelTitle))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        panelTitleBarLayout.setVerticalGroup(
            panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleBarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelIcon)
                    .addGroup(panelTitleBarLayout.createSequentialGroup()
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSubtitle)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelProjects.setBackground(java.awt.Color.white);
        panelProjects.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelProjects.setToolTipText("");

        labelProjectsTitle.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        labelProjectsTitle.setForeground(new java.awt.Color(0, 153, 102));
        labelProjectsTitle.setText("Projetos");

        labelProjectsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProjectsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelProjectsIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelProjectsLayout = new javax.swing.GroupLayout(panelProjects);
        panelProjects.setLayout(panelProjectsLayout);
        panelProjectsLayout.setHorizontalGroup(
            panelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(labelProjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelProjectsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelProjectsLayout.setVerticalGroup(
            panelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelProjectsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelProjectsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelTasks.setBackground(java.awt.Color.white);
        panelTasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTasksTitle.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        labelTasksTitle.setForeground(new java.awt.Color(0, 153, 102));
        labelTasksTitle.setText("Tarefas");

        labelTasksIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTasksLayout = new javax.swing.GroupLayout(panelTasks);
        panelTasks.setLayout(panelTasksLayout);
        panelTasksLayout.setHorizontalGroup(
            panelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTasksLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelTasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTasksIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTasksLayout.setVerticalGroup(
            panelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTasksTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTasksIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelProjectsList.setBackground(java.awt.Color.white);
        panelProjectsList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listProjects.setBackground(new java.awt.Color(255, 255, 255));
        listProjects.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        listProjects.setForeground(new java.awt.Color(51, 51, 51));
        listProjects.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listProjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listProjects.setFixedCellHeight(40);
        listProjects.setSelectionBackground(new java.awt.Color(0, 153, 102));
        scrollPanelProjects.setViewportView(listProjects);

        javax.swing.GroupLayout panelProjectsListLayout = new javax.swing.GroupLayout(panelProjectsList);
        panelProjectsList.setLayout(panelProjectsListLayout);
        panelProjectsListLayout.setHorizontalGroup(
            panelProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelProjects)
                .addContainerGap())
        );
        panelProjectsListLayout.setVerticalGroup(
            panelProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelProjects, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContentsTask.setBackground(java.awt.Color.white);
        panelContentsTask.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        scrollPanelTasks.setBackground(java.awt.Color.white);

        tableTasks.setBackground(java.awt.Color.white);
        tableTasks.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 12)); // NOI18N
        tableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTasks.setGridColor(java.awt.Color.white);
        tableTasks.setRowHeight(40);
        tableTasks.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tableTasks.setShowVerticalLines(false);
        scrollPanelTasks.setViewportView(tableTasks);

        javax.swing.GroupLayout panelContentsTaskLayout = new javax.swing.GroupLayout(panelContentsTask);
        panelContentsTask.setLayout(panelContentsTaskLayout);
        panelContentsTaskLayout.setHorizontalGroup(
            panelContentsTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );
        panelContentsTaskLayout.setVerticalGroup(
            panelContentsTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelContentsLayout = new javax.swing.GroupLayout(panelContents);
        panelContents.setLayout(panelContentsLayout);
        panelContentsLayout.setHorizontalGroup(
            panelContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitleBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContentsLayout.createSequentialGroup()
                        .addGroup(panelContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelContentsTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelContentsLayout.setVerticalGroup(
            panelContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContentsTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelProjectsIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelProjectsIconMouseClicked
        // TODO add your handling code here:
        ProjectDialogScreen dialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        dialogScreen.setVisible(true);
    }//GEN-LAST:event_labelProjectsIconMouseClicked
    
    public void decorateTableTask() {
        tableTasks.getTableHeader().setFont(new Font("DejaVu Sans Condensed", Font.BOLD, 14));
        tableTasks.getTableHeader().setBackground(new Color(0, 153, 102));
        tableTasks.getTableHeader().setForeground(new Color(255, 255, 255));
        tableTasks.setAutoCreateRowSorter(true);
        
    }//decorateTableTask

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
        
    }//main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelEmptyListIcon;
    private javax.swing.JLabel labelEmptyListSubtitle;
    private javax.swing.JLabel labelEmptyListTitle;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelProjectsIcon;
    private javax.swing.JLabel labelProjectsTitle;
    private javax.swing.JLabel labelSubtitle;
    private javax.swing.JLabel labelTasksIcon;
    private javax.swing.JLabel labelTasksTitle;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JList<String> listProjects;
    private javax.swing.JPanel panelContents;
    private javax.swing.JPanel panelContentsTask;
    private javax.swing.JPanel panelEmptyList;
    private javax.swing.JPanel panelProjects;
    private javax.swing.JPanel panelProjectsList;
    private javax.swing.JPanel panelTasks;
    private javax.swing.JPanel panelTitleBar;
    private javax.swing.JScrollPane scrollPanelProjects;
    private javax.swing.JScrollPane scrollPanelTasks;
    private javax.swing.JTable tableTasks;
    // End of variables declaration//GEN-END:variables

}//class
