/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.danilorocha.view;

import com.danilorocha.controllers.ProjectController;
import com.danilorocha.entities.Project;
import static com.danilorocha.entities.Project.newProject;
import static util.UtilView.message;
import static util.UtilView.checkInputs;
import java.time.LocalDateTime;

/**
 *
 * @author danilo
 */
public class ProjectDialogScreen extends javax.swing.JDialog {

    private ProjectController projectController;
    
    /**
     * Creates new form ProjectDialogScreen
     */
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        projectController = new ProjectController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitleBar = new javax.swing.JPanel();
        labelTitleBar = new javax.swing.JLabel();
        labelSaveProject = new javax.swing.JLabel();
        panelContentsProject = new javax.swing.JPanel();
        labelNameProject = new javax.swing.JLabel();
        inputNameProject = new javax.swing.JTextField();
        labelDescritionProject = new javax.swing.JLabel();
        scrollPanelDescriptionProject = new javax.swing.JScrollPane();
        textAreaDescriptionProject = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);

        panelTitleBar.setBackground(new java.awt.Color(0, 153, 102));

        labelTitleBar.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        labelTitleBar.setForeground(new java.awt.Color(255, 255, 255));
        labelTitleBar.setText("Projeto");

        labelSaveProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSaveProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        labelSaveProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSaveProjectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTitleBarLayout = new javax.swing.GroupLayout(panelTitleBar);
        panelTitleBar.setLayout(panelTitleBarLayout);
        panelTitleBarLayout.setHorizontalGroup(
            panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSaveProject, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTitleBarLayout.setVerticalGroup(
            panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSaveProject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelContentsProject.setBackground(java.awt.Color.white);

        labelNameProject.setBackground(java.awt.Color.white);
        labelNameProject.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        labelNameProject.setForeground(new java.awt.Color(128, 128, 128));
        labelNameProject.setText("Nome");

        inputNameProject.setBackground(java.awt.Color.white);
        inputNameProject.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        inputNameProject.setForeground(java.awt.Color.black);
        inputNameProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameProjectActionPerformed(evt);
            }
        });

        labelDescritionProject.setBackground(java.awt.Color.white);
        labelDescritionProject.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        labelDescritionProject.setForeground(new java.awt.Color(128, 128, 128));
        labelDescritionProject.setText("Descrição");

        textAreaDescriptionProject.setBackground(java.awt.Color.white);
        textAreaDescriptionProject.setColumns(20);
        textAreaDescriptionProject.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        textAreaDescriptionProject.setForeground(new java.awt.Color(0, 0, 0));
        textAreaDescriptionProject.setRows(5);
        scrollPanelDescriptionProject.setViewportView(textAreaDescriptionProject);

        javax.swing.GroupLayout panelContentsProjectLayout = new javax.swing.GroupLayout(panelContentsProject);
        panelContentsProject.setLayout(panelContentsProjectLayout);
        panelContentsProjectLayout.setHorizontalGroup(
            panelContentsProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContentsProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContentsProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPanelDescriptionProject)
                    .addComponent(labelNameProject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputNameProject, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescritionProject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelContentsProjectLayout.setVerticalGroup(
            panelContentsProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentsProjectLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelNameProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNameProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDescritionProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelDescriptionProject, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitleBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContentsProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContentsProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameProjectActionPerformed

    private void labelSaveProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSaveProjectMouseClicked
        // TODO add your handling code here:
        String name = inputNameProject.getText();
        String description = textAreaDescriptionProject.getText();

        if (checkInputs(rootPane, name, description)) {
            try {
                Project project = newProject(null, name, description, 
                LocalDateTime.now(), LocalDateTime.now());
                projectController.save(project);
                message(rootPane,"Salvo com sucesso");
            } catch (Exception e) {
                e.printStackTrace();
                message(rootPane, "Não foi possível salvar o projeto");
            } finally {
                this.dispose();
            }
        }//if
    }//GEN-LAST:event_labelSaveProjectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputNameProject;
    private javax.swing.JLabel labelDescritionProject;
    private javax.swing.JLabel labelNameProject;
    private javax.swing.JLabel labelSaveProject;
    private javax.swing.JLabel labelTitleBar;
    private javax.swing.JPanel panelContentsProject;
    private javax.swing.JPanel panelTitleBar;
    private javax.swing.JScrollPane scrollPanelDescriptionProject;
    private javax.swing.JTextArea textAreaDescriptionProject;
    // End of variables declaration//GEN-END:variables

}//class
