/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.danilorocha.view;

import com.danilorocha.controllers.TaskController;
import com.danilorocha.entities.Project;
import com.danilorocha.entities.Task;
import static com.danilorocha.view.UtilView.checkInputs;
import static com.danilorocha.view.UtilView.message;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;

/**
 *
 * @author danilo
 */
public class TaskDialogScreen extends javax.swing.JDialog {
    
    TaskController taskController;
    Project project;

    /**
     * Creates new form ProjectDialogScreen
     */
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        taskController = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitleBar = new javax.swing.JPanel();
        labelTitleBar = new javax.swing.JLabel();
        labelSaveTask = new javax.swing.JLabel();
        panelNameDescriptionTask = new javax.swing.JPanel();
        labelNameTask = new javax.swing.JLabel();
        inputNameTask = new javax.swing.JTextField();
        labelDescriptionTask = new javax.swing.JLabel();
        scrollPanelDescriptionTask = new javax.swing.JScrollPane();
        textAreaDescriptionTask = new javax.swing.JTextArea();
        panelDeadlineNotesTask = new javax.swing.JPanel();
        labelDeadlineTask = new javax.swing.JLabel();
        labelNotesTask = new javax.swing.JLabel();
        scrollPanelNotesTask = new javax.swing.JScrollPane();
        textAreaNotesTask = new javax.swing.JTextArea();
        inputDeadlineTask = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);

        panelTitleBar.setBackground(new java.awt.Color(0, 153, 102));

        labelTitleBar.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        labelTitleBar.setForeground(new java.awt.Color(255, 255, 255));
        labelTitleBar.setText("Tarefa");

        labelSaveTask.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSaveTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        labelSaveTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSaveTaskMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTitleBarLayout = new javax.swing.GroupLayout(panelTitleBar);
        panelTitleBar.setLayout(panelTitleBarLayout);
        panelTitleBarLayout.setHorizontalGroup(
            panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSaveTask, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTitleBarLayout.setVerticalGroup(
            panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSaveTask, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelNameDescriptionTask.setBackground(java.awt.Color.white);

        labelNameTask.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        labelNameTask.setForeground(new java.awt.Color(128, 128, 128));
        labelNameTask.setText("Nome");

        inputNameTask.setBackground(java.awt.Color.white);
        inputNameTask.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        inputNameTask.setForeground(java.awt.Color.white);
        inputNameTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameTaskActionPerformed(evt);
            }
        });

        labelDescriptionTask.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        labelDescriptionTask.setForeground(new java.awt.Color(128, 128, 128));
        labelDescriptionTask.setText("Descrição");

        textAreaDescriptionTask.setBackground(java.awt.Color.white);
        textAreaDescriptionTask.setColumns(20);
        textAreaDescriptionTask.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        textAreaDescriptionTask.setRows(5);
        scrollPanelDescriptionTask.setViewportView(textAreaDescriptionTask);

        javax.swing.GroupLayout panelNameDescriptionTaskLayout = new javax.swing.GroupLayout(panelNameDescriptionTask);
        panelNameDescriptionTask.setLayout(panelNameDescriptionTaskLayout);
        panelNameDescriptionTaskLayout.setHorizontalGroup(
            panelNameDescriptionTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNameDescriptionTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNameDescriptionTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPanelDescriptionTask, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(labelNameTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputNameTask, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescriptionTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelNameDescriptionTaskLayout.setVerticalGroup(
            panelNameDescriptionTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameDescriptionTaskLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNameTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNameTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDescriptionTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelDescriptionTask, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelDeadlineNotesTask.setBackground(java.awt.Color.white);

        labelDeadlineTask.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        labelDeadlineTask.setForeground(new java.awt.Color(128, 128, 128));
        labelDeadlineTask.setText("Prazo");

        labelNotesTask.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        labelNotesTask.setForeground(new java.awt.Color(128, 128, 128));
        labelNotesTask.setText("Notas");

        textAreaNotesTask.setBackground(java.awt.Color.white);
        textAreaNotesTask.setColumns(20);
        textAreaNotesTask.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        textAreaNotesTask.setRows(5);
        scrollPanelNotesTask.setViewportView(textAreaNotesTask);

        inputDeadlineTask.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        inputDeadlineTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDeadlineTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeadlineNotesTaskLayout = new javax.swing.GroupLayout(panelDeadlineNotesTask);
        panelDeadlineNotesTask.setLayout(panelDeadlineNotesTaskLayout);
        panelDeadlineNotesTaskLayout.setHorizontalGroup(
            panelDeadlineNotesTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeadlineNotesTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeadlineNotesTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanelNotesTask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(labelDeadlineTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNotesTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputDeadlineTask))
                .addContainerGap())
        );
        panelDeadlineNotesTaskLayout.setVerticalGroup(
            panelDeadlineNotesTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeadlineNotesTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDeadlineTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputDeadlineTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNotesTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelNotesTask, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitleBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNameDescriptionTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDeadlineNotesTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNameDescriptionTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDeadlineNotesTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameTaskActionPerformed

    private void labelSaveTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSaveTaskMouseClicked
        // TODO add your handling code here:
        String name = inputNameTask.getText();
        String description = textAreaDescriptionTask.getText();
        String notes = textAreaNotesTask.getText();
        String deadline = inputDeadlineTask.getText();
        
        if (checkInputs(rootPane, name, description, deadline)) {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            try {
                Task task = Task.newTask(null, project.getId(), name,
                        description, notes, false, LocalDate.parse(deadline, dtf),
                        LocalDateTime.now(), LocalDateTime.now());
                taskController.save(task);
                message(rootPane, "Tarefa salva com sucesso");
            } catch (Exception e) {
                e.printStackTrace();
                message(rootPane, "Não foi possível salvar a tarefa");
            } finally {
                this.dispose();
            }
        }//if
    }//GEN-LAST:event_labelSaveTaskMouseClicked

    private void inputDeadlineTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDeadlineTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDeadlineTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField inputDeadlineTask;
    private javax.swing.JTextField inputNameTask;
    private javax.swing.JLabel labelDeadlineTask;
    private javax.swing.JLabel labelDescriptionTask;
    private javax.swing.JLabel labelNameTask;
    private javax.swing.JLabel labelNotesTask;
    private javax.swing.JLabel labelSaveTask;
    private javax.swing.JLabel labelTitleBar;
    private javax.swing.JPanel panelDeadlineNotesTask;
    private javax.swing.JPanel panelNameDescriptionTask;
    private javax.swing.JPanel panelTitleBar;
    private javax.swing.JScrollPane scrollPanelDescriptionTask;
    private javax.swing.JScrollPane scrollPanelNotesTask;
    private javax.swing.JTextArea textAreaDescriptionTask;
    private javax.swing.JTextArea textAreaNotesTask;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }   
    
}
